from distutils.core import setup

setup(
    name='epa7658577',
    version='',
    packages=['blog', 'blog.migrations', 'core', 'core.migrations', 'nutr', 'nutr.urls', 'nutr.migrations', 'user',
              'user.migrations', 'venv.lib.python3.4.distutils', 'venv.lib.python3.4.encodings',
              'venv.lib.python3.4.importlib', 'venv.lib.python3.4.collections', 'venv.lib.python3.4.site-packages.pip',
              'venv.lib.python3.4.site-packages.pip.req', 'venv.lib.python3.4.site-packages.pip.vcs',
              'venv.lib.python3.4.site-packages.pip.utils', 'venv.lib.python3.4.site-packages.pip.compat',
              'venv.lib.python3.4.site-packages.pip.models', 'venv.lib.python3.4.site-packages.pip._vendor',
              'venv.lib.python3.4.site-packages.pip._vendor.distlib',
              'venv.lib.python3.4.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.4.site-packages.pip._vendor.colorama',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.4.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.4.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.4.site-packages.pip._vendor.progress',
              'venv.lib.python3.4.site-packages.pip._vendor.requests',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.4.site-packages.pip._vendor.packaging',
              'venv.lib.python3.4.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.4.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.4.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.4.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.4.site-packages.pip.commands', 'venv.lib.python3.4.site-packages.pip.operations',
              'venv.lib.python3.4.site-packages.wheel', 'venv.lib.python3.4.site-packages.wheel.test',
              'venv.lib.python3.4.site-packages.wheel.test.simple.dist.simpledist',
              'venv.lib.python3.4.site-packages.wheel.test.complex-dist.complexdist',
              'venv.lib.python3.4.site-packages.wheel.tool', 'venv.lib.python3.4.site-packages.wheel.signatures',
              'venv.lib.python3.4.site-packages.django', 'venv.lib.python3.4.site-packages.django.db',
              'venv.lib.python3.4.site-packages.django.db.models',
              'venv.lib.python3.4.site-packages.django.db.models.sql',
              'venv.lib.python3.4.site-packages.django.db.models.fields',
              'venv.lib.python3.4.site-packages.django.db.backends',
              'venv.lib.python3.4.site-packages.django.db.backends.base',
              'venv.lib.python3.4.site-packages.django.db.backends.dummy',
              'venv.lib.python3.4.site-packages.django.db.backends.mysql',
              'venv.lib.python3.4.site-packages.django.db.backends.oracle',
              'venv.lib.python3.4.site-packages.django.db.backends.sqlite3',
              'venv.lib.python3.4.site-packages.django.db.backends.postgresql',
              'venv.lib.python3.4.site-packages.django.db.backends.postgresql_psycopg2',
              'venv.lib.python3.4.site-packages.django.db.migrations',
              'venv.lib.python3.4.site-packages.django.db.migrations.operations',
              'venv.lib.python3.4.site-packages.django.apps', 'venv.lib.python3.4.site-packages.django.conf',
              'venv.lib.python3.4.site-packages.django.conf.urls',
              'venv.lib.python3.4.site-packages.django.conf.locale',
              'venv.lib.python3.4.site-packages.django.conf.locale.ar',
              'venv.lib.python3.4.site-packages.django.conf.locale.az',
              'venv.lib.python3.4.site-packages.django.conf.locale.bg',
              'venv.lib.python3.4.site-packages.django.conf.locale.bn',
              'venv.lib.python3.4.site-packages.django.conf.locale.bs',
              'venv.lib.python3.4.site-packages.django.conf.locale.ca',
              'venv.lib.python3.4.site-packages.django.conf.locale.cs',
              'venv.lib.python3.4.site-packages.django.conf.locale.cy',
              'venv.lib.python3.4.site-packages.django.conf.locale.da',
              'venv.lib.python3.4.site-packages.django.conf.locale.de',
              'venv.lib.python3.4.site-packages.django.conf.locale.el',
              'venv.lib.python3.4.site-packages.django.conf.locale.en',
              'venv.lib.python3.4.site-packages.django.conf.locale.eo',
              'venv.lib.python3.4.site-packages.django.conf.locale.es',
              'venv.lib.python3.4.site-packages.django.conf.locale.et',
              'venv.lib.python3.4.site-packages.django.conf.locale.eu',
              'venv.lib.python3.4.site-packages.django.conf.locale.fa',
              'venv.lib.python3.4.site-packages.django.conf.locale.fi',
              'venv.lib.python3.4.site-packages.django.conf.locale.fr',
              'venv.lib.python3.4.site-packages.django.conf.locale.fy',
              'venv.lib.python3.4.site-packages.django.conf.locale.ga',
              'venv.lib.python3.4.site-packages.django.conf.locale.gd',
              'venv.lib.python3.4.site-packages.django.conf.locale.gl',
              'venv.lib.python3.4.site-packages.django.conf.locale.he',
              'venv.lib.python3.4.site-packages.django.conf.locale.hi',
              'venv.lib.python3.4.site-packages.django.conf.locale.hr',
              'venv.lib.python3.4.site-packages.django.conf.locale.hu',
              'venv.lib.python3.4.site-packages.django.conf.locale.id',
              'venv.lib.python3.4.site-packages.django.conf.locale.is',
              'venv.lib.python3.4.site-packages.django.conf.locale.it',
              'venv.lib.python3.4.site-packages.django.conf.locale.ja',
              'venv.lib.python3.4.site-packages.django.conf.locale.ka',
              'venv.lib.python3.4.site-packages.django.conf.locale.km',
              'venv.lib.python3.4.site-packages.django.conf.locale.kn',
              'venv.lib.python3.4.site-packages.django.conf.locale.ko',
              'venv.lib.python3.4.site-packages.django.conf.locale.lt',
              'venv.lib.python3.4.site-packages.django.conf.locale.lv',
              'venv.lib.python3.4.site-packages.django.conf.locale.mk',
              'venv.lib.python3.4.site-packages.django.conf.locale.ml',
              'venv.lib.python3.4.site-packages.django.conf.locale.mn',
              'venv.lib.python3.4.site-packages.django.conf.locale.nb',
              'venv.lib.python3.4.site-packages.django.conf.locale.nl',
              'venv.lib.python3.4.site-packages.django.conf.locale.nn',
              'venv.lib.python3.4.site-packages.django.conf.locale.pl',
              'venv.lib.python3.4.site-packages.django.conf.locale.pt',
              'venv.lib.python3.4.site-packages.django.conf.locale.ro',
              'venv.lib.python3.4.site-packages.django.conf.locale.ru',
              'venv.lib.python3.4.site-packages.django.conf.locale.sk',
              'venv.lib.python3.4.site-packages.django.conf.locale.sl',
              'venv.lib.python3.4.site-packages.django.conf.locale.sq',
              'venv.lib.python3.4.site-packages.django.conf.locale.sr',
              'venv.lib.python3.4.site-packages.django.conf.locale.sv',
              'venv.lib.python3.4.site-packages.django.conf.locale.ta',
              'venv.lib.python3.4.site-packages.django.conf.locale.te',
              'venv.lib.python3.4.site-packages.django.conf.locale.th',
              'venv.lib.python3.4.site-packages.django.conf.locale.tr',
              'venv.lib.python3.4.site-packages.django.conf.locale.uk',
              'venv.lib.python3.4.site-packages.django.conf.locale.vi',
              'venv.lib.python3.4.site-packages.django.conf.locale.de_CH',
              'venv.lib.python3.4.site-packages.django.conf.locale.en_AU',
              'venv.lib.python3.4.site-packages.django.conf.locale.en_GB',
              'venv.lib.python3.4.site-packages.django.conf.locale.es_AR',
              'venv.lib.python3.4.site-packages.django.conf.locale.es_CO',
              'venv.lib.python3.4.site-packages.django.conf.locale.es_MX',
              'venv.lib.python3.4.site-packages.django.conf.locale.es_NI',
              'venv.lib.python3.4.site-packages.django.conf.locale.es_PR',
              'venv.lib.python3.4.site-packages.django.conf.locale.pt_BR',
              'venv.lib.python3.4.site-packages.django.conf.locale.sr_Latn',
              'venv.lib.python3.4.site-packages.django.conf.locale.zh_Hans',
              'venv.lib.python3.4.site-packages.django.conf.locale.zh_Hant',
              'venv.lib.python3.4.site-packages.django.core', 'venv.lib.python3.4.site-packages.django.core.mail',
              'venv.lib.python3.4.site-packages.django.core.mail.backends',
              'venv.lib.python3.4.site-packages.django.core.cache',
              'venv.lib.python3.4.site-packages.django.core.cache.backends',
              'venv.lib.python3.4.site-packages.django.core.files',
              'venv.lib.python3.4.site-packages.django.core.checks',
              'venv.lib.python3.4.site-packages.django.core.checks.security',
              'venv.lib.python3.4.site-packages.django.core.checks.compatibility',
              'venv.lib.python3.4.site-packages.django.core.servers',
              'venv.lib.python3.4.site-packages.django.core.handlers',
              'venv.lib.python3.4.site-packages.django.core.management',
              'venv.lib.python3.4.site-packages.django.core.management.commands',
              'venv.lib.python3.4.site-packages.django.core.serializers',
              'venv.lib.python3.4.site-packages.django.http', 'venv.lib.python3.4.site-packages.django.test',
              'venv.lib.python3.4.site-packages.django.forms', 'venv.lib.python3.4.site-packages.django.forms.extras',
              'venv.lib.python3.4.site-packages.django.utils',
              'venv.lib.python3.4.site-packages.django.utils.translation',
              'venv.lib.python3.4.site-packages.django.views', 'venv.lib.python3.4.site-packages.django.views.generic',
              'venv.lib.python3.4.site-packages.django.views.decorators',
              'venv.lib.python3.4.site-packages.django.contrib', 'venv.lib.python3.4.site-packages.django.contrib.gis',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.models',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.models.sql',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.backends',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.backends.base',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.backends.mysql',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.backends.oracle',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.backends.postgis',
              'venv.lib.python3.4.site-packages.django.contrib.gis.db.backends.spatialite',
              'venv.lib.python3.4.site-packages.django.contrib.gis.gdal',
              'venv.lib.python3.4.site-packages.django.contrib.gis.gdal.raster',
              'venv.lib.python3.4.site-packages.django.contrib.gis.gdal.prototypes',
              'venv.lib.python3.4.site-packages.django.contrib.gis.geos',
              'venv.lib.python3.4.site-packages.django.contrib.gis.geos.prototypes',
              'venv.lib.python3.4.site-packages.django.contrib.gis.maps',
              'venv.lib.python3.4.site-packages.django.contrib.gis.maps.google',
              'venv.lib.python3.4.site-packages.django.contrib.gis.maps.openlayers',
              'venv.lib.python3.4.site-packages.django.contrib.gis.admin',
              'venv.lib.python3.4.site-packages.django.contrib.gis.forms',
              'venv.lib.python3.4.site-packages.django.contrib.gis.geoip',
              'venv.lib.python3.4.site-packages.django.contrib.gis.utils',
              'venv.lib.python3.4.site-packages.django.contrib.gis.geoip2',
              'venv.lib.python3.4.site-packages.django.contrib.gis.geometry',
              'venv.lib.python3.4.site-packages.django.contrib.gis.geometry.backend',
              'venv.lib.python3.4.site-packages.django.contrib.gis.sitemaps',
              'venv.lib.python3.4.site-packages.django.contrib.gis.management',
              'venv.lib.python3.4.site-packages.django.contrib.gis.management.commands',
              'venv.lib.python3.4.site-packages.django.contrib.gis.serializers',
              'venv.lib.python3.4.site-packages.django.contrib.auth',
              'venv.lib.python3.4.site-packages.django.contrib.auth.tests',
              'venv.lib.python3.4.site-packages.django.contrib.auth.handlers',
              'venv.lib.python3.4.site-packages.django.contrib.auth.management',
              'venv.lib.python3.4.site-packages.django.contrib.auth.management.commands',
              'venv.lib.python3.4.site-packages.django.contrib.auth.migrations',
              'venv.lib.python3.4.site-packages.django.contrib.admin',
              'venv.lib.python3.4.site-packages.django.contrib.admin.views',
              'venv.lib.python3.4.site-packages.django.contrib.admin.migrations',
              'venv.lib.python3.4.site-packages.django.contrib.admin.templatetags',
              'venv.lib.python3.4.site-packages.django.contrib.sites',
              'venv.lib.python3.4.site-packages.django.contrib.sites.migrations',
              'venv.lib.python3.4.site-packages.django.contrib.humanize',
              'venv.lib.python3.4.site-packages.django.contrib.humanize.templatetags',
              'venv.lib.python3.4.site-packages.django.contrib.messages',
              'venv.lib.python3.4.site-packages.django.contrib.messages.storage',
              'venv.lib.python3.4.site-packages.django.contrib.postgres',
              'venv.lib.python3.4.site-packages.django.contrib.postgres.forms',
              'venv.lib.python3.4.site-packages.django.contrib.postgres.fields',
              'venv.lib.python3.4.site-packages.django.contrib.postgres.aggregates',
              'venv.lib.python3.4.site-packages.django.contrib.sessions',
              'venv.lib.python3.4.site-packages.django.contrib.sessions.backends',
              'venv.lib.python3.4.site-packages.django.contrib.sessions.management',
              'venv.lib.python3.4.site-packages.django.contrib.sessions.management.commands',
              'venv.lib.python3.4.site-packages.django.contrib.sessions.migrations',
              'venv.lib.python3.4.site-packages.django.contrib.sitemaps',
              'venv.lib.python3.4.site-packages.django.contrib.sitemaps.management',
              'venv.lib.python3.4.site-packages.django.contrib.sitemaps.management.commands',
              'venv.lib.python3.4.site-packages.django.contrib.admindocs',
              'venv.lib.python3.4.site-packages.django.contrib.admindocs.tests',
              'venv.lib.python3.4.site-packages.django.contrib.flatpages',
              'venv.lib.python3.4.site-packages.django.contrib.flatpages.migrations',
              'venv.lib.python3.4.site-packages.django.contrib.flatpages.templatetags',
              'venv.lib.python3.4.site-packages.django.contrib.redirects',
              'venv.lib.python3.4.site-packages.django.contrib.redirects.migrations',
              'venv.lib.python3.4.site-packages.django.contrib.webdesign',
              'venv.lib.python3.4.site-packages.django.contrib.webdesign.templatetags',
              'venv.lib.python3.4.site-packages.django.contrib.staticfiles',
              'venv.lib.python3.4.site-packages.django.contrib.staticfiles.management',
              'venv.lib.python3.4.site-packages.django.contrib.staticfiles.management.commands',
              'venv.lib.python3.4.site-packages.django.contrib.staticfiles.templatetags',
              'venv.lib.python3.4.site-packages.django.contrib.syndication',
              'venv.lib.python3.4.site-packages.django.contrib.contenttypes',
              'venv.lib.python3.4.site-packages.django.contrib.contenttypes.migrations',
              'venv.lib.python3.4.site-packages.django.dispatch', 'venv.lib.python3.4.site-packages.django.template',
              'venv.lib.python3.4.site-packages.django.template.loaders',
              'venv.lib.python3.4.site-packages.django.template.backends',
              'venv.lib.python3.4.site-packages.django.middleware',
              'venv.lib.python3.4.site-packages.django.templatetags', 'venv.lib.python3.4.site-packages.gunicorn',
              'venv.lib.python3.4.site-packages.gunicorn.app', 'venv.lib.python3.4.site-packages.gunicorn.http',
              'venv.lib.python3.4.site-packages.gunicorn.workers',
              'venv.lib.python3.4.site-packages.gunicorn.instrument',
              'venv.lib.python3.4.site-packages.gunicorn.management',
              'venv.lib.python3.4.site-packages.gunicorn.management.commands',
              'venv.lib.python3.4.site-packages.psycopg2', 'venv.lib.python3.4.site-packages.psycopg2.tests',
              'venv.lib.python3.4.site-packages.requests', 'venv.lib.python3.4.site-packages.requests.packages',
              'venv.lib.python3.4.site-packages.requests.packages.chardet',
              'venv.lib.python3.4.site-packages.requests.packages.urllib3',
              'venv.lib.python3.4.site-packages.requests.packages.urllib3.util',
              'venv.lib.python3.4.site-packages.requests.packages.urllib3.contrib',
              'venv.lib.python3.4.site-packages.requests.packages.urllib3.packages',
              'venv.lib.python3.4.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.4.site-packages.setuptools', 'venv.lib.python3.4.site-packages.setuptools.extern',
              'venv.lib.python3.4.site-packages.setuptools.command', 'venv.lib.python3.4.site-packages.whitenoise',
              'venv.lib.python3.4.site-packages.whitenoise.management',
              'venv.lib.python3.4.site-packages.whitenoise.management.commands',
              'venv.lib.python3.4.site-packages.pkg_resources', 'venv.lib.python3.4.site-packages.pkg_resources.extern',
              'venv.lib.python3.4.site-packages.pkg_resources._vendor',
              'venv.lib.python3.4.site-packages.pkg_resources._vendor.packaging', 'epa7658577',
              'myprojectenv.lib.python3.4.distutils', 'myprojectenv.lib.python3.4.encodings',
              'myprojectenv.lib.python3.4.importlib', 'myprojectenv.lib.python3.4.collections',
              'myprojectenv.lib.python3.4.site-packages.pip', 'myprojectenv.lib.python3.4.site-packages.pip.req',
              'myprojectenv.lib.python3.4.site-packages.pip.vcs', 'myprojectenv.lib.python3.4.site-packages.pip.utils',
              'myprojectenv.lib.python3.4.site-packages.pip.compat',
              'myprojectenv.lib.python3.4.site-packages.pip.models',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.distlib',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.distlib._backport',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.colorama',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.html5lib',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.html5lib._trie',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.html5lib.filters',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.html5lib.treewalkers',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.html5lib.treeadapters',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.html5lib.treebuilders',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.lockfile',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.progress',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages.chardet',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.util',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.packaging',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.cachecontrol',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.cachecontrol.caches',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.webencodings',
              'myprojectenv.lib.python3.4.site-packages.pip._vendor.pkg_resources',
              'myprojectenv.lib.python3.4.site-packages.pip.commands',
              'myprojectenv.lib.python3.4.site-packages.pip.operations',
              'myprojectenv.lib.python3.4.site-packages.wheel', 'myprojectenv.lib.python3.4.site-packages.wheel.test',
              'myprojectenv.lib.python3.4.site-packages.wheel.test.simple.dist.simpledist',
              'myprojectenv.lib.python3.4.site-packages.wheel.test.complex-dist.complexdist',
              'myprojectenv.lib.python3.4.site-packages.wheel.tool',
              'myprojectenv.lib.python3.4.site-packages.wheel.signatures',
              'myprojectenv.lib.python3.4.site-packages.setuptools',
              'myprojectenv.lib.python3.4.site-packages.setuptools.extern',
              'myprojectenv.lib.python3.4.site-packages.setuptools.command',
              'myprojectenv.lib.python3.4.site-packages.pkg_resources',
              'myprojectenv.lib.python3.4.site-packages.pkg_resources.extern',
              'myprojectenv.lib.python3.4.site-packages.pkg_resources._vendor',
              'myprojectenv.lib.python3.4.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='michaelsweeney',
    author_email='',
    description=''
)
