# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_sites_data'),
    ]

    operations = [
    ]
