# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='nutr.Tag', verbose_name='Country'),
        ),
    ]
