# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nutr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(max_length=63)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
                'verbose_name': 'news article',
            },
        ),
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(upload_to=nutr.models.generate_upload_path)),
                ('link', models.URLField(max_length=2550)),
                ('created_date', models.DateField(verbose_name='Date Account Created')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='poc',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutr.Tag'),
        ),
        migrations.AddField(
            model_name='newslink',
            name='poc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutr.POC'),
        ),
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together=set([('slug', 'poc')]),
        ),
    ]
