# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-04 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 4, 16, 56, 22, 301167, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 4, 16, 56, 22, 301048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='poc',
            name='tag',
            field=models.ForeignKey(default=1229, on_delete=django.db.models.deletion.CASCADE, to='nutr.Tag', verbose_name='Country'),
        ),
    ]
