# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={},
        ),
        migrations.AddField(
            model_name='poc',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 6, 21, 15, 49, 17, 742545, tzinfo=utc), upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together=set([]),
        ),
    ]
