# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
