# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutr.Tag'),
        ),
    ]
