# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0002_auto_20170627_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=2550),
            preserve_default=False,
        ),
    ]
