# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 16:17
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0002_auto_20170621_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='images'), upload_to=''),
        ),
    ]
