# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0002_auto_20170810_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='description',
            field=models.TextField(max_length=1800),
        ),
    ]
