# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nutr.models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0003_poc_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'news article'},
        ),
        migrations.AlterField(
            model_name='newslink',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutr.POC'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nutr.models.generate_upload_path),
        ),
    ]
