# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0003_auto_20170812_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
