# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0003_auto_20170621_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='image',
            field=models.ImageField(upload_to='nutr'),
        ),
    ]
