# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import nutr.models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0004_auto_20170621_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='image',
            field=models.ImageField(upload_to=nutr.models.generate_upload_path),
        ),
    ]
