# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0005_poc_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newslink',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poc',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poc',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=255, unique=True),
        ),
    ]
