# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-03 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0005_auto_20170903_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='amnesty',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='poc',
            name='hrw',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Yes'), (False, 'No')]),
        ),
    ]
