# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import nutr.models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0006_auto_20170709_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 7, 11, 19, 15, 7, 517989, tzinfo=utc), upload_to=nutr.models.generate_upload_path),
            preserve_default=False,
        ),
    ]
