# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-03 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0006_auto_20170903_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='amnesty',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poc',
            name='hrw',
            field=models.NullBooleanField(default=False),
        ),
    ]
