# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-12 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0007_auto_20170903_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='charge',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poc',
            name='status',
            field=models.CharField(choices=[('P', 'Prisoner'), ('R', 'Released'), ('A', 'Re-arrested'), ('E', 'Executed'), ('D', 'Deceased')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='poc',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 15, 10, 53, 233270, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='poc',
            name='hrw',
            field=models.NullBooleanField(default=False, verbose_name='HRW'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poc',
            name='tag',
            field=models.ForeignKey(default=1324, on_delete=django.db.models.deletion.CASCADE, to='nutr.Tag', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 15, 10, 53, 233374, tzinfo=utc)),
        ),
    ]
