# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-12 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0011_auto_20170912_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poc',
            name='arrest_date',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='trial_date',
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 22, 16, 7, 626868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 12, 22, 16, 7, 626998, tzinfo=utc)),
        ),
    ]
