# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-23 16:06
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutr', '0012_auto_20170912_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_nutr_poc_set', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='poc',
            name='created_with_session_key',
            field=audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='poc',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_nutr_poc_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='poc',
            name='modified_with_session_key',
            field=audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 16, 6, 22, 214369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 23, 16, 6, 22, 214471, tzinfo=utc)),
        ),
    ]
