# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-24 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0015_auto_20170923_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='action_user',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='tag',
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 16, 16, 6, 565768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 16, 16, 6, 565872, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='POCAuditLogEntry',
        ),
    ]
