# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-24 19:01
from __future__ import unicode_literals

import audit_log.models.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import nutr.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutr', '0016_auto_20170924_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='POCAuditLogEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(upload_to=nutr.models.generate_upload_path)),
                ('link', models.URLField(max_length=2550)),
                ('created_date', models.DateField(default=datetime.datetime(2017, 9, 24, 19, 1, 39, 433069, tzinfo=utc))),
                ('description', models.TextField(max_length=2500)),
                ('amnesty', models.NullBooleanField(default=False)),
                ('hrw', models.NullBooleanField(default=False, verbose_name='HRW')),
                ('updated_date', models.DateField(default=datetime.datetime(2017, 9, 24, 19, 1, 39, 433171, tzinfo=utc))),
                ('status', models.CharField(choices=[('P', 'Prisoner'), ('R', 'Released'), ('A', 'Re-arrested'), ('E', 'Executed'), ('D', 'Deceased')], max_length=1, null=True)),
                ('judge', models.TextField(blank=True, max_length=255, null=True, verbose_name='Presiding Judge')),
                ('arrested_date', models.DateField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('trial_date', models.DateField(blank=True, null=True)),
                ('charge', models.TextField(blank=True, max_length=255, null=True)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_type', models.CharField(choices=[('I', 'Created'), ('U', 'Changed'), ('D', 'Deleted')], editable=False, max_length=1)),
                ('action_user', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_poc_audit_log_entry', to=settings.AUTH_USER_MODEL)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_auditlog_created_nutr_poc_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_auditlog_modified_nutr_poc_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('tag', models.ForeignKey(default=1324, on_delete=django.db.models.deletion.CASCADE, to='nutr.Tag', verbose_name='Country')),
            ],
            options={
                'default_permissions': (),
                'ordering': ('-action_date',),
            },
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 19, 1, 39, 433069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 19, 1, 39, 433171, tzinfo=utc)),
        ),
    ]
