# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-24 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0017_auto_20170924_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poc',
            name='arrested_date',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='trial_date',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='arrested_date',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='released_date',
        ),
        migrations.RemoveField(
            model_name='pocauditlogentry',
            name='trial_date',
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 19, 51, 5, 500071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 19, 51, 5, 500173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 19, 51, 5, 500071, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 19, 51, 5, 500173, tzinfo=utc)),
        ),
    ]
