# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-27 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0020_auto_20170927_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='judge',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Presiding Judge'),
        ),
        migrations.AddField(
            model_name='poc',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pocauditlogentry',
            name='judge',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Presiding Judge'),
        ),
        migrations.AddField(
            model_name='pocauditlogentry',
            name='trial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 27, 20, 20, 54, 974278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 27, 20, 20, 54, 974385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 27, 20, 20, 54, 974278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 27, 20, 20, 54, 974385, tzinfo=utc)),
        ),
    ]
