# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-05 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0027_auto_20171010_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc',
            name='charge',
            field=models.TextField(default=datetime.datetime(2017, 11, 5, 21, 38, 7, 360217, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 37, 56, 147109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='status',
            field=models.CharField(choices=[('P', 'Prisoner'), ('Q', 'Disappeared'), ('R', 'Released'), ('A', 'Re-arrested'), ('E', 'Executed'), ('D', 'Deceased'), ('S', 'Escaped')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 37, 56, 147285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='charge',
            field=models.TextField(default=datetime.datetime(2017, 11, 5, 21, 38, 14, 167820, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 37, 56, 147109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='status',
            field=models.CharField(choices=[('P', 'Prisoner'), ('Q', 'Disappeared'), ('R', 'Released'), ('A', 'Re-arrested'), ('E', 'Executed'), ('D', 'Deceased'), ('S', 'Escaped')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 37, 56, 147285, tzinfo=utc)),
        ),
    ]
