# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-05 21:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutr', '0028_auto_20171105_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc',
            name='changed_by',
            field=models.ForeignKey(default=datetime.datetime(2017, 11, 5, 21, 41, 14, 998071, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='nutr_pocs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pocauditlogentry',
            name='changed_by',
            field=models.ForeignKey(default=datetime.datetime(2017, 11, 5, 21, 41, 22, 364572, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='_auditlog_nutr_pocs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poc',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 41, 0, 629216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='poc',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 41, 0, 629324, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 41, 0, 629216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pocauditlogentry',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 21, 41, 0, 629324, tzinfo=utc)),
        ),
    ]
