# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='newslink',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='poc',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='NewsLink',
        ),
        migrations.DeleteModel(
            name='POC',
        ),
    ]
